# this code installs python and running unit test cases on addition code 
name: My first Github Actions
on: 
 push :
  branches : master

jobs : 
 build-test-deploy: 
  runs-on : ubuntu-latest
  
  steps :
  - uses: actions/checkout@v3
  - name: set up python
    uses: actions/checkout@v2
    with: 
     python-version: 3.8
     
  - name: Install Dependencies
    run: |
     python -m pip install --upgrade pip
     pip install pytest
  - name: Run test
    run: |
       cd src
       python -m pytest addition.py  
